version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: ems-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: employeeDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: ems-server
    restart: always
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017/employeeDB
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: ems-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data:
